WIP: [feat samuray90] [pug sass javaScript scss css html] project refresher 4
codetapacademy/my-cv-v2-junior pull request #170
Opened 2020-10-05 16:49 UTC by samuray90

2020-10-05 16:55 UTC, marianzburlea requested changes

2020-10-05 16:55 UTC, marianzburlea commented on src/_component/connect/connect.pug
> +.column(span="row" height="10")
you're using 2 spaces tabs for indentation

2020-10-05 16:55 UTC, marianzburlea commented on src/_component/connect/connect.pug
> +.column(span="row")
You're using 4 spaces indentation

2020-10-05 16:55 UTC, marianzburlea commented on src/_component/connect/connect.scss
> +        background-image: url('asset/image/poza.jpg');
use **baseUrl** to assure it will work on GitHub as well.

2020-10-05 16:55 UTC, marianzburlea commented on src/_data/about-me.json
> +        "Describe yourself here erfuhnerhfdwersjerwjwerjhfdwerhjfsdrwejfdswrejhfdjfsdhjfsdjfsd",
add proper content

2020-10-05 17:50 UTC, samuray90 commented on src/_data/about-me.json
> +        "Describe yourself here erfuhnerhfdwersjerwjwerjhfdwerhjfsdrwejfdswrejhfdjfsdhjfsdjfsd",
replaced with something more professional.

2020-10-07 10:13 UTC, marianzburlea approved these changes

2020-10-20 19:12 UTC, ValentinaVanu approved these changes

2020-12-24 15:52 UTC, marianzburlea approved these changes

2020-12-24 15:52 UTC, merged