WIP:dev-robertoalx-v3-about-me
codetapacademy/my-cv-v2-junior pull request #237
Opened 2021-03-02 23:51 UTC by robertoalx

2021-03-05 00:41 UTC, marianzburlea approved these changes
💯

2021-03-05 00:42 UTC, blowymind99 approved these changes
💯

2021-03-05 00:45 UTC, QuintyHH requested changes

2021-03-05 00:45 UTC, QuintyHH commented on src/_data/about.json
> +  "sectionHeader": "Welcome to my Sanctuar",
Misspelled 'Sanctuary'

2021-03-05 00:45 UTC, QuintyHH commented on src/style.scss
> +@import '_asset/font/style'
Please add a newline

2021-03-05 00:45 UTC, QuintyHH commented on src/_component/base/source-code-pro-font.scss
> +}
Please add a newline

2021-03-05 00:51 UTC, adelacecilia approved these changes
Good job, Rob! 👍 💯

2021-03-05 03:24 UTC, psyhedeliq approved these changes
🤘

2021-03-05 06:07 UTC, BogdanNegura approved these changes
👍

2021-03-05 06:47 UTC, RalucaRbc commented on src/_component/about/about.scss
> +  &main-title{
Just for readability, you may need an empty space between the class name and `{`

2021-03-05 06:47 UTC, RalucaRbc commented on src/_component/about/about.pug
> +    .section__header=data['about'].sectionHeader
Nothing wrong with your  `data['about'].sectionHeader` but you could have had just `data.about.sectionHeader` as you don't have any special character like `-` in the name of your file about.json

2021-03-05 06:49 UTC, RalucaRbc approved these changes
Well done overall Robert 🚀

2021-03-05 12:40 UTC, marianzburlea approved these changes
💯

2021-03-05 21:00 UTC, biggicode approved these changes

2021-03-07 08:24 UTC, MariaTeo approved these changes
Nice work overall

2021-03-07 08:24 UTC, MariaTeo commented on src/_asset/font/style.scss
> +}
Empty line needed for readability

2021-03-07 08:24 UTC, MariaTeo commented on src/_asset/font/style.scss
> +}
Empty line needed for readability

2021-03-07 08:24 UTC, MariaTeo commented on src/_asset/font/style.scss
> +}
Empty line needed for readability

2021-03-07 08:24 UTC, MariaTeo commented on src/_asset/font/style.scss
> +}
Empty line needed for readability

2021-03-07 08:24 UTC, MariaTeo commented on src/_asset/font/style.scss
> +}
And so on

2021-03-08 15:22 UTC, marianzburlea approved these changes

2021-03-08 15:22 UTC, merged