WIP: add content to the intro section
codetapacademy/my-cv-v2-junior pull request #239
Opened 2021-03-04 11:50 UTC by adelacecilia

2021-03-07 08:40 UTC, MariaTeo reviewed
Great start! Keep it up 👌🏼

2021-03-10 07:45 UTC, samuray90 approved these changes
🔟 cool!

2021-03-12 01:46 UTC, andreimaff approved these changes
looks nice 👍🏼

2021-03-12 07:11 UTC, RalucaRbc approved these changes
Looks nice and clean overall 💯 (You may need just a new empty line at the end of each file, but you're doing great so far anyway ❤️ )

2021-03-12 19:17 UTC, marianzburlea requested changes
small changes

2021-03-12 19:17 UTC, marianzburlea commented on src/_component/about-me/about-me.pug
> +    p.description=data['about-me'].descriptionList[0]
loop the `data['about-me'].descriptionList` collection using `each`
ask for help if you don't know how to do it

2021-03-12 23:03 UTC, marianzburlea approved these changes
:100

2021-03-14 11:49 UTC, merged