WIP: dev screpyy96 menu
codetapacademy/my-cv-v2-junior pull request #273
Opened 2021-03-16 19:04 UTC by screpyy96

2021-03-28 22:59 UTC, RalucaRbc approved these changes

2021-03-28 23:01 UTC, marianzburlea requested changes
minor changes

2021-03-28 23:01 UTC, marianzburlea commented on src/_component/_connect/connect.pug
>  -var sectionTitle= data.connect.sectionTitle
add space before =

2021-03-28 23:01 UTC, marianzburlea commented on src/_component/_connect/connect.pug
>  -var sectionTitle= data.connect.sectionTitle
and before `var`

2021-03-28 23:01 UTC, marianzburlea commented on src/_component/menu/menu.pug
> +  input.toggler(type='checkbox' id="toggler")
use double quotes for values of attributes

2021-03-28 23:01 UTC, marianzburlea commented on src/_component/menu/menu.pug
> +          a(href=`${item.link}`)=item.title
you don't need to use backticks when there is only the value
`a(href=item.link)= item.title`

2021-03-29 10:23 UTC, marianzburlea approved these changes
💯

2021-03-29 10:24 UTC, merged