Dev mariateo embeded Youtube video
codetapacademy/my-cv-v2-junior pull request #282
Opened 2021-03-25 22:02 UTC by MariaTeo

2021-03-25 22:06 UTC, biggicode approved these changes

2021-03-25 22:06 UTC, Constantin-Matei approved these changes
✔

2021-03-25 22:07 UTC, marianzburlea requested changes
make the youtube button work

2021-03-25 22:07 UTC, marianzburlea commented on src/_component/section-title/section-title.pug
> +  iframe(src="https://www.youtube.com/embed/G7RgN9ijwE4"  title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
separate attributes on multiple lines
```
iframe(
  src="https://www.youtube.com/embed/G7RgN9ijwE4"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
)
```

2021-03-30 07:14 UTC, adelacecilia approved these changes
Nice :)

2021-03-30 07:15 UTC, biggicode approved these changes

2021-03-30 07:16 UTC, Constantin-Matei approved these changes

2021-03-30 07:17 UTC, Adrian01C approved these changes
niceee

2021-03-30 07:25 UTC, RalucaRbc approved these changes
💯

2021-03-30 09:54 UTC, simonamarcu2 approved these changes
Nice work!

2021-03-30 13:17 UTC, marianzburlea approved these changes
💯

2021-03-30 13:17 UTC, marianzburlea commented on src/_component/section-title/section-title.scss
> +  transform: translate(-50%,-50%) scale();
Add extra space and remove the scale if you're not using it.
`transform: translate(-50%, -50%);`

2021-03-30 13:17 UTC, marianzburlea commented on src/_component/section-title/section-title.scss
> +  transform: translate(-50%,-50%) scale(1);
Add extra space
`  transform: translate(-50%, -50%) scale(1);`

2021-03-30 13:17 UTC, marianzburlea commented on src/index.pug
> +          title="YouTube video player" frameborder="0"
press <kbd>Enter</kbd> beofer frameborder:

```
title="YouTube video player"
frameborder="0" 
```

2021-03-30 13:17 UTC, marianzburlea commented on src/index.pug
> +          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
same for `allowfullscreen`

2021-03-31 02:56 UTC, adelacecilia commented
Looks nice! :D

2021-03-31 08:07 UTC, merged